/* Generated by socgen/memmap.py. Do not edit; edit the map and regenerate. */

#ifndef SOC_MAP_H
#define SOC_MAP_H

#include <stdint.h>

#define MMIO(addr) (*(volatile uint32_t *)(addr))

/* Data memory. The core's instruction memory is separate and not on this bus. */
#define RAM_BASE  0x00000000u
#define RAM_SIZE  0x00010000u

/* UART transmitter and receiver with a synchronous FIFO. */
#define UART_BASE  0x10000000u
#define UART_SIZE  0x00001000u
#define UART_DATA  0x10000000u  /* write: byte to transmit; read: oldest received byte */
#define UART_STAT  0x10000004u  /* status flags, read-only */
#define UART_DIV  0x10000008u  /* baud divisor: CLK_HZ/baud - 1 */
#define UART_CTRL  0x1000000Cu  /* frame format */
#define UART_IRQ_EN  0x10000010u  /* interrupt enable mask */
#define UART_IRQ_STAT  0x10000014u  /* interrupt status, write 1 to clear */

/* SPI master covering all four clock modes. */
#define SPI_BASE  0x10001000u
#define SPI_SIZE  0x00001000u
#define SPI_DATA  0x10001000u  /* write starts a transfer; read returns the received byte */
#define SPI_STATUS  0x10001004u  /* bit0 busy */
#define SPI_CONFIG  0x10001008u  /* bit0 CPOL, bit1 CPHA, bits15:8 clock divisor */

/* AES-128 accelerator. Key and block are written 32 bits at a time. */
#define AES_BASE  0x20000000u
#define AES_SIZE  0x00001000u
#define AES_KEY0  0x20000000u  /* key bits 31:0 */
#define AES_KEY1  0x20000004u  /* key bits 63:32 */
#define AES_KEY2  0x20000008u  /* key bits 95:64 */
#define AES_KEY3  0x2000000Cu  /* key bits 127:96 */
#define AES_DATA0  0x20000010u  /* plaintext bits 31:0 */
#define AES_DATA1  0x20000014u  /* plaintext bits 63:32 */
#define AES_DATA2  0x20000018u  /* plaintext bits 95:64 */
#define AES_DATA3  0x2000001Cu  /* plaintext bits 127:96 */
#define AES_CTRL  0x20000020u  /* write 1 to start */
#define AES_STATUS  0x20000024u  /* bit0 done */
#define AES_OUT0  0x20000030u  /* ciphertext bits 31:0 */
#define AES_OUT1  0x20000034u  /* ciphertext bits 63:32 */
#define AES_OUT2  0x20000038u  /* ciphertext bits 95:64 */
#define AES_OUT3  0x2000003Cu  /* ciphertext bits 127:96 */

/* Core-local interruptor: the machine timer and the software interrupt. The offsets are SiFive's, because every RISC-V bootloader already expects them; mtime at 0xBFF8 is why the window is 64 KB and not 4 KB like the others. */
#define CLINT_BASE  0x40000000u
#define CLINT_SIZE  0x00010000u
#define CLINT_MSIP  0x40000000u  /* bit0: raise the machine software interrupt */
#define CLINT_MTIMECMP_LO  0x40004000u  /* timer deadline, bits 31:0 */
#define CLINT_MTIMECMP_HI  0x40004004u  /* timer deadline, bits 63:32 */
#define CLINT_MTIME_LO  0x4000BFF8u  /* free-running counter, bits 31:0, read-only */
#define CLINT_MTIME_HI  0x4000BFFCu  /* free-running counter, bits 63:32, read-only */

/* Ring-oscillator entropy source, von Neumann de-biased and whitened. VHDL, so it attaches at synthesis rather than in the mixed-language simulation. */
#define TRNG_BASE  0x30000000u
#define TRNG_SIZE  0x00001000u
#define TRNG_DATA  0x30000000u  /* read: one whitened random byte */
#define TRNG_STATUS  0x30000004u  /* bit0 valid */

#endif /* SOC_MAP_H */
