// Generated by socgen/memmap.py. Do not edit; edit the map and regenerate.

`ifndef SOC_MAP_SVH
`define SOC_MAP_SVH

// Data memory. The core's instruction memory is separate and not on this bus.
localparam logic [31:0] RAM_BASE = 32'h00000000;
localparam logic [31:0] RAM_SIZE = 32'h00010000;
localparam logic [31:0] RAM_LIMIT = 32'h0000FFFF;

// UART transmitter and receiver with a synchronous FIFO.
localparam logic [31:0] UART_BASE = 32'h10000000;
localparam logic [31:0] UART_SIZE = 32'h00001000;
localparam logic [31:0] UART_LIMIT = 32'h10000FFF;
localparam logic [31:0] UART_DATA = 32'h10000000;  // write: byte to transmit; read: oldest received byte
localparam logic [31:0] UART_STAT = 32'h10000004;  // status flags, read-only
localparam logic [31:0] UART_DIV = 32'h10000008;  // baud divisor: CLK_HZ/baud - 1
localparam logic [31:0] UART_CTRL = 32'h1000000C;  // frame format
localparam logic [31:0] UART_IRQ_EN = 32'h10000010;  // interrupt enable mask
localparam logic [31:0] UART_IRQ_STAT = 32'h10000014;  // interrupt status, write 1 to clear

// SPI master covering all four clock modes.
localparam logic [31:0] SPI_BASE = 32'h10001000;
localparam logic [31:0] SPI_SIZE = 32'h00001000;
localparam logic [31:0] SPI_LIMIT = 32'h10001FFF;
localparam logic [31:0] SPI_DATA = 32'h10001000;  // write starts a transfer; read returns the received byte
localparam logic [31:0] SPI_STATUS = 32'h10001004;  // bit0 busy
localparam logic [31:0] SPI_CONFIG = 32'h10001008;  // bit0 CPOL, bit1 CPHA, bits15:8 clock divisor

// AES-128 accelerator. Key and block are written 32 bits at a time.
localparam logic [31:0] AES_BASE = 32'h20000000;
localparam logic [31:0] AES_SIZE = 32'h00001000;
localparam logic [31:0] AES_LIMIT = 32'h20000FFF;
localparam logic [31:0] AES_KEY0 = 32'h20000000;  // key bits 31:0
localparam logic [31:0] AES_KEY1 = 32'h20000004;  // key bits 63:32
localparam logic [31:0] AES_KEY2 = 32'h20000008;  // key bits 95:64
localparam logic [31:0] AES_KEY3 = 32'h2000000C;  // key bits 127:96
localparam logic [31:0] AES_DATA0 = 32'h20000010;  // plaintext bits 31:0
localparam logic [31:0] AES_DATA1 = 32'h20000014;  // plaintext bits 63:32
localparam logic [31:0] AES_DATA2 = 32'h20000018;  // plaintext bits 95:64
localparam logic [31:0] AES_DATA3 = 32'h2000001C;  // plaintext bits 127:96
localparam logic [31:0] AES_CTRL = 32'h20000020;  // write 1 to start
localparam logic [31:0] AES_STATUS = 32'h20000024;  // bit0 done
localparam logic [31:0] AES_OUT0 = 32'h20000030;  // ciphertext bits 31:0
localparam logic [31:0] AES_OUT1 = 32'h20000034;  // ciphertext bits 63:32
localparam logic [31:0] AES_OUT2 = 32'h20000038;  // ciphertext bits 95:64
localparam logic [31:0] AES_OUT3 = 32'h2000003C;  // ciphertext bits 127:96

// Core-local interruptor: the machine timer and the software interrupt. The offsets are SiFive's, because every RISC-V bootloader already expects them; mtime at 0xBFF8 is why the window is 64 KB and not 4 KB like the others.
localparam logic [31:0] CLINT_BASE = 32'h40000000;
localparam logic [31:0] CLINT_SIZE = 32'h00010000;
localparam logic [31:0] CLINT_LIMIT = 32'h4000FFFF;
localparam logic [31:0] CLINT_MSIP = 32'h40000000;  // bit0: raise the machine software interrupt
localparam logic [31:0] CLINT_MTIMECMP_LO = 32'h40004000;  // timer deadline, bits 31:0
localparam logic [31:0] CLINT_MTIMECMP_HI = 32'h40004004;  // timer deadline, bits 63:32
localparam logic [31:0] CLINT_MTIME_LO = 32'h4000BFF8;  // free-running counter, bits 31:0, read-only
localparam logic [31:0] CLINT_MTIME_HI = 32'h4000BFFC;  // free-running counter, bits 63:32, read-only

// Ring-oscillator entropy source, von Neumann de-biased and whitened. VHDL, so it attaches at synthesis rather than in the mixed-language simulation.
localparam logic [31:0] TRNG_BASE = 32'h30000000;
localparam logic [31:0] TRNG_SIZE = 32'h00001000;
localparam logic [31:0] TRNG_LIMIT = 32'h30000FFF;
localparam logic [31:0] TRNG_DATA = 32'h30000000;  // read: one whitened random byte
localparam logic [31:0] TRNG_STATUS = 32'h30000004;  // bit0 valid

`endif
