// note_to_phase.v — MIDI note-number → DDS phase increment lookup ROM.
//
// 128-entry synchronous ROM.  Entry n holds the 32-bit DDS phase increment
// for MIDI note n at the configured sample rate:
//
//   phase_inc[n] = round(f(n) / Fs × 2^32)
//   f(n) = 440 × 2^((n−69)/12)     (equal temperament, A4 = 440 Hz)
//
// Initialised from note_phase_48k.hex which is generated by the
// accompanying Python script gen_hex.py.
//
// Latency: 1 clock cycle (synchronous ROM).

module note_to_phase #(
    parameter FS = 48000   // sample rate (informational only; hex pre-computed)
) (
    input  wire       clk,
    input  wire [6:0] note,       // MIDI note 0–127 (7 bits)
    output reg  [31:0] phase_inc  // DDS phase increment
);

    reg [31:0] rom [0:127];

    initial begin
        $readmemh("note_phase_48k.hex", rom);
    end

    always @(posedge clk)
        phase_inc <= rom[note];

endmodule
